import Foundation

/// Z.ai (智谱 / BigModel) usage adapter.
///
/// Preferred auth is the Coding Plan API key generated by the local ZCode
/// installation. A key pasted in Settings remains available as a fallback.
/// We GET `api/monitor/usage/quota/limit` with the raw API key in the
/// Authorization header, matching ZCode's own quota client, and parse the
/// response into one to three `QuotaBucket`s
/// (token limit primary, session token limit secondary if the API
/// returns multiple TOKENS_LIMIT entries, time limit tertiary).
///
/// Region selection follows codexbar's reader:
/// 1. `Z_AI_QUOTA_URL` env var — full URL override.
/// 2. `Z_AI_API_HOST` env var — host/base URL override.
/// 3. `MiscProviderSettings.enterpriseHost` — same effect as 2.
/// 4. `MiscProviderSettings.region` — `"global"` or `"bigmodel-cn"`.
/// 5. Default — global.
public struct ZaiQuotaAdapter: QuotaAdapter {
    public let tool: ToolType = .zai

    private let session: URLSession
    private let environment: [String: String]
    private let now: @Sendable () -> Date
    private let nativeCredentialResolver: @Sendable () throws -> ZCodeCredential

    public init(
        session: URLSession = .shared,
        environment: [String: String] = ProcessInfo.processInfo.environment,
        now: @escaping @Sendable () -> Date = { Date() },
        nativeCredentialResolver: (@Sendable () throws -> ZCodeCredential)? = nil
    ) {
        self.session = session
        self.environment = environment
        self.now = now
        self.nativeCredentialResolver = nativeCredentialResolver ?? {
            try ZCodeCredentialReader.load()
        }
    }

    public func fetch(for account: AccountIdentity) async throws -> AccountQuota {
        let queriedAt = now()
        var nativeError: QuotaError?
        do {
            let credential = try nativeCredentialResolver()
            return try await fetchQuota(
                url: credential.quotaURL,
                authorization: credential.apiKey,
                account: account,
                fallbackPlan: credential.planName,
                queriedAt: queriedAt
            )
        } catch let error as QuotaError {
            nativeError = error
        } catch {
            nativeError = .noCredential
        }

        let instanceID = AccountStore.miscInstanceID(fromAccountID: account.id, fallbackTool: .zai)
        let providerSettings = MiscProviderSettings.current(for: .zai, instanceID: instanceID)
        guard providerSettings.allowsAPIOrOAuthAccess else {
            throw nativeError ?? QuotaError.noCredential
        }
        let settings = ZaiSettings.resolve(
            environment: environment,
            providerSettings: providerSettings
        )

        guard let apiKey = MiscCredentialStore.readString(tool: .zai, kind: .apiKey, instanceID: instanceID),
              !apiKey.isEmpty
        else {
            throw nativeError ?? QuotaError.noCredential
        }

        return try await fetchQuota(
            url: settings.quotaURL,
            authorization: apiKey,
            account: account,
            fallbackPlan: account.plan,
            queriedAt: queriedAt
        )
    }

    private func fetchQuota(
        url: URL,
        authorization: String,
        account: AccountIdentity,
        fallbackPlan: String?,
        queriedAt: Date
    ) async throws -> AccountQuota {
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.timeoutInterval = 15
        request.setValue(authorization, forHTTPHeaderField: "Authorization")
        request.setValue("application/json", forHTTPHeaderField: "Accept")

        let (data, response): (Data, URLResponse)
        do {
            (data, response) = try await session.data(for: request)
        } catch {
            throw QuotaError.network("Z.ai network error: \(error.localizedDescription)")
        }

        guard let http = response as? HTTPURLResponse else {
            throw QuotaError.network("Z.ai: invalid response object")
        }
        guard http.statusCode == 200 else {
            if http.statusCode == 401 || http.statusCode == 403 {
                throw QuotaError.needsLogin
            }
            if http.statusCode == 429 {
                throw QuotaError.rateLimited
            }
            throw QuotaError.network("Z.ai returned HTTP \(http.statusCode).")
        }
        guard !data.isEmpty else {
            throw QuotaError.parseFailure("Z.ai returned an empty body — confirm the region (Global vs BigModel CN) and the API key.")
        }

        let snapshot = try ZaiResponseParser.parse(data: data, now: queriedAt)
        return AccountQuota(
            accountId: account.id,
            tool: .zai,
            buckets: snapshot.buckets,
            plan: snapshot.planName ?? fallbackPlan,
            email: account.email,
            queriedAt: queriedAt,
            error: nil
        )
    }
}

// MARK: - Region / endpoint resolution

struct ZaiSettings {
    let quotaURL: URL

    static func resolve(
        environment: [String: String],
        providerSettings: MiscProviderSettings = .default
    ) -> ZaiSettings {
        if let raw = environment["Z_AI_QUOTA_URL"]?
            .trimmingCharacters(in: .whitespacesAndNewlines),
           !raw.isEmpty,
           let url = URL(string: raw),
           url.scheme != nil
        {
            return ZaiSettings(quotaURL: url)
        }

        if let host = environment["Z_AI_API_HOST"]?
            .trimmingCharacters(in: .whitespacesAndNewlines),
           !host.isEmpty,
           let url = quotaURL(fromHost: host)
        {
            return ZaiSettings(quotaURL: url)
        }

        if let host = providerSettings.enterpriseHost?.absoluteString,
           let url = quotaURL(fromHost: host) {
            return ZaiSettings(quotaURL: url)
        }

        if let rawRegion = providerSettings.region?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased(),
           let region = ZaiRegion(rawValue: rawRegion) {
            return ZaiSettings(quotaURL: region.quotaURL)
        }

        return ZaiSettings(quotaURL: ZaiRegion.global.quotaURL)
    }

    static func quotaURL(fromHost host: String) -> URL? {
        var trimmed = host.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return nil }
        if !trimmed.contains("://") {
            trimmed = "https://\(trimmed)"
        }
        return URL(string: trimmed)?.appendingPathComponent("api/monitor/usage/quota/limit")
    }
}

enum ZaiRegion: String {
    case global
    case bigmodelCN = "bigmodel-cn"

    var baseURL: URL {
        switch self {
        case .global:     return URL(string: "https://api.z.ai")!
        case .bigmodelCN: return URL(string: "https://open.bigmodel.cn")!
        }
    }

    var quotaURL: URL {
        baseURL.appendingPathComponent("api/monitor/usage/quota/limit")
    }
}

// MARK: - Response parsing

enum ZaiResponseParser {
    struct Snapshot {
        var buckets: [QuotaBucket]
        var planName: String?
    }

    static func parse(data: Data, now: Date) throws -> Snapshot {
        let decoder = JSONDecoder()
        let response: ZaiAPIResponse
        do {
            response = try decoder.decode(ZaiAPIResponse.self, from: data)
        } catch {
            throw QuotaError.parseFailure("Z.ai response not parseable: \(error.localizedDescription)")
        }
        guard response.success, response.code == 200 else {
            throw QuotaError.network("Z.ai API error: \(response.msg)")
        }
        guard let body = response.data else {
            throw QuotaError.parseFailure("Z.ai response missing data envelope.")
        }

        var tokenLimits: [QuotaBucket] = []
        var timeLimit: QuotaBucket?

        for raw in body.limits {
            guard let bucket = raw.toBucket(now: now) else { continue }
            switch raw.type {
            case "TOKENS_LIMIT", "CREDIT_LIMIT": tokenLimits.append(bucket)
            case "TIME_LIMIT":   timeLimit = bucket
            default:             continue
            }
        }

        // Match codexbar: with two TOKENS_LIMIT entries, the shorter
        // window is the secondary "session" bucket and the longer is
        // primary. Single entry → primary only.
        let primaryAndSecondary: [QuotaBucket]
        if tokenLimits.count >= 2 {
            let sorted = tokenLimits.sorted {
                ($0.rawWindowSeconds ?? .max) > ($1.rawWindowSeconds ?? .max)
            }
            // sorted[0] = longest window (primary), sorted[1] = shortest (secondary)
            primaryAndSecondary = Array(sorted.prefix(2))
        } else {
            primaryAndSecondary = tokenLimits
        }

        var buckets = primaryAndSecondary
        if let timeLimit { buckets.append(timeLimit) }
        guard !buckets.isEmpty else {
            throw QuotaError.parseFailure("Z.ai response contained no supported quota limits.")
        }

        return Snapshot(buckets: buckets, planName: body.planName)
    }
}

// MARK: - Wire types

private struct ZaiAPIResponse: Decodable {
    let code: Int
    let msg: String
    let data: ZaiAPIData?
    let success: Bool
}

private struct ZaiAPIData: Decodable {
    let limits: [ZaiRawLimit]
    let planName: String?

    enum CodingKeys: String, CodingKey {
        case limits, planName, plan, level
        case planType = "plan_type"
        case packageName
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        limits = try c.decodeIfPresent([ZaiRawLimit].self, forKey: .limits) ?? []
        let candidates: [String?] = [
            try c.decodeIfPresent(String.self, forKey: .planName),
            try c.decodeIfPresent(String.self, forKey: .plan),
            try c.decodeIfPresent(String.self, forKey: .planType),
            try c.decodeIfPresent(String.self, forKey: .packageName)
        ]
        let raw = candidates.compactMap(\.self).first?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        if let raw, !raw.isEmpty {
            planName = raw
        } else if let level = try c.decodeIfPresent(String.self, forKey: .level)?
            .trimmingCharacters(in: .whitespacesAndNewlines),
            !level.isEmpty
        {
            planName = "GLM Coding \(level.prefix(1).uppercased())\(level.dropFirst().lowercased())"
        } else {
            planName = nil
        }
    }
}

private struct ZaiRawLimit: Decodable {
    let type: String
    let unit: Int
    let number: Int
    let usage: Int?
    let currentValue: Int?
    let remaining: Int?
    let percentage: Int
    let nextResetTime: Int?

    /// Maps the API's enum-as-int unit to seconds. Unknown values
    /// drop through to nil so the bucket renders with "Resets ..."
    /// hidden rather than crashing.
    var windowSeconds: Int? {
        switch unit {
        case 1: return number * 86_400        // days
        case 3: return number * 3_600         // hours
        case 5: return number * 30 * 86_400   // months
        case 6: return number * 7 * 86_400    // weeks
        default: return nil
        }
    }

    func toBucket(now: Date) -> QuotaBucket? {
        // Title is "5 Hours" / "Daily" / "Weekly" / "Monthly" derived
        // from window. Falls back to a generic label otherwise.
        let title: String
        let shortLabel: String
        switch unit {
        case 1:
            title = number == 1 ? "Daily" : "\(number) Days"
            shortLabel = number == 1 ? "Day" : "\(number)d"
        case 3:
            title = "\(number) Hour\(number == 1 ? "" : "s")"
            shortLabel = "\(number)h"
        case 5:
            if type == "TIME_LIMIT" {
                title = number == 1 ? "MCP Monthly" : "MCP \(number) Months"
            } else {
                title = number == 1 ? "Monthly" : "\(number) Months"
            }
            shortLabel = number == 1 ? "Month" : "\(number)mo"
        case 6:
            title = number == 1 ? "Weekly" : "\(number) Weeks"
            shortLabel = number == 1 ? "Wk" : "\(number)w"
        default:
            title = type == "TIME_LIMIT" ? "Monthly" : "Tokens"
            shortLabel = type == "TIME_LIMIT" ? "Month" : "Tok"
        }

        // Compute used percent. Codexbar prefers `(usage - remaining) / usage * 100`
        // when both are present; otherwise it falls back to the
        // server-supplied integer percentage. Mirror that.
        let computed: Double
        if let usage, usage > 0, let remaining {
            let used = max(0, usage - remaining)
            computed = (Double(used) / Double(usage)) * 100
        } else {
            computed = Double(percentage)
        }

        let resetAt = nextResetTime.map {
            Date(timeIntervalSince1970: TimeInterval($0) / 1000)
        }

        let id: String
        switch type {
        case "TIME_LIMIT":   id = "zai.time"
        case "TOKENS_LIMIT": id = "zai.tokens.\(unit).\(number)"
        case "CREDIT_LIMIT": id = "zai.credits.\(unit).\(number)"
        default:             id = "zai.\(type.lowercased()).\(unit).\(number)"
        }

        var bucket = QuotaBucket(
            id: id,
            title: title,
            shortLabel: shortLabel,
            usedPercent: computed,
            resetAt: resetAt,
            rawWindowSeconds: windowSeconds
        )
        // Annotate token-limit buckets with a group title so the UI
        // can disambiguate primary from session-window when both are
        // present.
        if type == "TOKENS_LIMIT" || type == "CREDIT_LIMIT" {
            bucket.groupTitle = title
        }
        _ = bucket
        return bucket
    }
}
